[package]
name = "reddit-search"
version = "0.1.0"
edition = "2021"
authors = ["Luc Aggett <luc@aggett.com>"]
description = "A search tool for the pushshift.io Reddit dumps."
license = "MIT"
repository = "https://github.com/lucaggett/reddit-search"
categories = ["command-line-utilities"]

[dependencies]
zstd = "0.12.4"
serde = "1.0.180"
serde_json = "1.0.67"
chrono = "0.4.19"
csv = "1.1.6"
log = "0.4.14"
clap = { version = "4.3.19", features = ["derive"] }
indicatif = "0.17.5"
rayon = "1.5.1"

[profile.release]
debug = 0
opt-level = 3