name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
        - name: Rust Release
          uses: manoadamro/rust-release@v1
          with:
            owner: lucaggett
            repo: reddit-search
            token: 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
            cargo: Cargo.toml
            dry_run: false
